# Generated by Django 5.2.14 on 2026-06-01 10:26

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'verbose_name': 'Video Index Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='VideoPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('video_url', models.URLField(verbose_name='URL e videos (YouTube / Vimeo)')),
                ('category', models.CharField(choices=[('education', 'Edukim'), ('rights', 'Të Drejta'), ('health', 'Shëndetësi'), ('economy', 'Ekonomi'), ('environment', 'Mjedis'), ('other', 'Tjetër')], default='other', max_length=20)),
                ('description', wagtail.fields.RichTextField(blank=True, verbose_name='Pershkrimi i videos')),
                ('presenter', models.CharField(blank=True, max_length=200, verbose_name='Prezantuesi / Eksperti')),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='Kohëzgjatja (minuta)')),
                ('cover_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Foto thumbnail (opsionale)')),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
            },
            bases=('wagtailcore.page',),
        ),
    ]
