# Generated by Django 5.2.14 on 2026-06-01 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Emri i agjencisë')),
                ('feed_url', models.URLField(unique=True, verbose_name='URL e RSS feed')),
                ('language', models.CharField(choices=[('sq', 'Shqip'), ('mk', 'Maqedonisht'), ('en', 'Anglisht')], default='sq', max_length=2)),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('last_fetched', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Feed Source',
                'verbose_name_plural': 'Feed Sources',
            },
        ),
        migrations.AddField(
            model_name='newsarticlepage',
            name='source_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='newsarticlepage',
            name='source_url',
            field=models.URLField(blank=True, db_index=True),
        ),
    ]
