# Generated by Django 5.2.14 on 2026-06-01 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_feedsource_newsarticlepage_source_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticlepage',
            name='source_url',
            field=models.URLField(blank=True, db_index=True, max_length=500),
        ),
    ]
