# Generated by Django 5.2.14 on 2026-06-02 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_increase_source_url_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newscategory',
            options={'ordering': ['name'], 'verbose_name': 'News Category', 'verbose_name_plural': 'News Categories'},
        ),
        migrations.AddField(
            model_name='newsarticlepage',
            name='language',
            field=models.CharField(choices=[('sq', 'Shqip'), ('mk', 'Maqedonisht'), ('en', 'Anglisht')], default='sq', max_length=2, verbose_name='Gjuha'),
        ),
        migrations.AlterField(
            model_name='newscategory',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Emri'),
        ),
    ]
