# Generated by Django 5.2.14 on 2026-06-05 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_newsarticlepage_language_newscategory_snippet'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticlepage',
            name='intro_en',
            field=models.TextField(blank=True, help_text='English translation (AI)', max_length=600),
        ),
        migrations.AddField(
            model_name='newsarticlepage',
            name='intro_mk',
            field=models.TextField(blank=True, help_text='Превод македонски (AI)', max_length=600),
        ),
        migrations.AddField(
            model_name='newsarticlepage',
            name='intro_sq',
            field=models.TextField(blank=True, help_text='Përkthim shqip (AI)', max_length=600),
        ),
    ]
