# Generated by Django 5.2.14 on 2026-06-01 10:26

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='GovIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'verbose_name': 'Government Index Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='GovItemPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('item_type', models.CharField(choices=[('tender', 'Tender'), ('grant', 'Grant / Fond'), ('competition', 'Konkurs'), ('law', 'Ligj / Rregullore'), ('announcement', 'Njoftim')], default='announcement', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Aktiv'), ('upcoming', 'Se shpejti'), ('expired', 'Ka skaduar')], default='active', max_length=20)),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Afati')),
                ('institution', models.CharField(blank=True, max_length=200, verbose_name='Institucioni')),
                ('budget', models.CharField(blank=True, max_length=100, verbose_name='Shuma / Buxheti')),
                ('original_url', models.URLField(blank=True, verbose_name='Linku origjinal zyrtar')),
                ('simple_explanation', wagtail.fields.RichTextField(help_text='Shpjego në gjuhë të thjeshtë çfarë është, kush mund të aplikojë, dhe si.', verbose_name='Shpjegimi i thjeshtë për qytetarët')),
                ('how_to_apply', wagtail.fields.StreamField([('step', 3), ('document_needed', 1), ('external_link', 5)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 3}), 1: ('wagtail.blocks.CharBlock', (), {}), 2: ('wagtail.blocks.RichTextBlock', (), {}), 3: ('wagtail.blocks.StructBlock', [[('number', 0), ('title', 1), ('description', 2)]], {}), 4: ('wagtail.blocks.URLBlock', (), {}), 5: ('wagtail.blocks.StructBlock', [[('title', 1), ('url', 4)]], {})}, verbose_name='Hapat e aplikimit')),
            ],
            options={
                'verbose_name': 'Government Item',
                'verbose_name_plural': 'Government Items',
            },
            bases=('wagtailcore.page',),
        ),
    ]
