# Generated by Django 5.2.14 on 2026-06-02 14:15

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('government', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GovSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Emri i burimit')),
                ('url', models.URLField(unique=True, verbose_name='URL (RSS ose faqe)')),
                ('institution', models.CharField(blank=True, max_length=200, verbose_name='Institucioni')),
                ('default_item_type', models.CharField(choices=[('tender', 'Tender'), ('grant', 'Grant / Fond'), ('competition', 'Konkurs'), ('law', 'Ligj / Rregullore'), ('announcement', 'Njoftim')], default='announcement', max_length=20, verbose_name='Lloji i parazgjedhur')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('last_fetched', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Gov Source',
                'verbose_name_plural': 'Gov Sources',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='govitempage',
            name='source_url',
            field=models.URLField(blank=True, db_index=True, max_length=500, verbose_name='URL burimi (per deduplikim)'),
        ),
        migrations.AlterField(
            model_name='govitempage',
            name='original_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='Linku origjinal zyrtar'),
        ),
        migrations.AlterField(
            model_name='govitempage',
            name='simple_explanation',
            field=wagtail.fields.RichTextField(blank=True, help_text='Shpjego në gjuhë të thjeshtë çfarë është, kush mund të aplikojë, dhe si.', verbose_name='Shpjegimi i thjeshtë për qytetarët'),
        ),
    ]
