# Generated by Django 5.2.14 on 2026-06-04 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('government', '0002_add_govsource_and_source_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='govitempage',
            name='documents_required',
            field=models.TextField(blank=True, help_text='Një dokument për rresht', verbose_name='Dokumentet e nevojshme'),
        ),
        migrations.AddField(
            model_name='govitempage',
            name='domain',
            field=models.CharField(blank=True, choices=[('bujqesi', 'Bujqësi'), ('blegtori', 'Blegtori'), ('rural', 'Zhvillim Rural'), ('social', 'Social / Familje'), ('punesim', 'Punësim'), ('biznes', 'Biznes / SME'), ('ambient', 'Ambient / Energji'), ('arsim', 'Arsim / Rini'), ('shendet', 'Shëndetësi'), ('tjeter', 'Tjetër')], default='tjeter', help_text='Fusha: bujqësi, blegtori, social, punësim...', max_length=20, verbose_name='Domeni'),
        ),
        migrations.AddField(
            model_name='govitempage',
            name='eligible_who',
            field=models.TextField(blank=True, help_text='Kushtet e eligibilitetit — kush mund të aplikojë', verbose_name='Kush ka të drejtë'),
        ),
        migrations.AlterField(
            model_name='govitempage',
            name='item_type',
            field=models.CharField(choices=[('tender', 'Tender'), ('grant', 'Grant / Fond'), ('competition', 'Konkurs'), ('law', 'Ligj / Rregullore'), ('announcement', 'Njoftim'), ('subsidy', 'Subvencion'), ('loan', 'Kredi / Hua')], default='announcement', max_length=20),
        ),
        migrations.AlterField(
            model_name='govsource',
            name='default_item_type',
            field=models.CharField(choices=[('tender', 'Tender'), ('grant', 'Grant / Fond'), ('competition', 'Konkurs'), ('law', 'Ligj / Rregullore'), ('announcement', 'Njoftim'), ('subsidy', 'Subvencion'), ('loan', 'Kredi / Hua')], default='announcement', max_length=20, verbose_name='Lloji i parazgjedhur'),
        ),
    ]
